### ISSUE TITLE
gh-pages is 404

### ISSUE THREAD

**Issue by awaxa** [discord-diabetes/diabot-plugins#13]
http://reddit-diabetes.github.io/diabot-plugins

This may only be a delay due to the repository transfer?

**Comment by liz-baker** [comment]
There was never a working GH pages page for it before.

**Comment by liz-baker** [comment]
oh wait this is 12B's repo.

**Comment by TwelveBaud** [comment]
There was a working GH Pages page when it lived in my account. It could be that GH Jekyll is still rebuilding it after the transfer, or that it needs a fresh commit to kick off a build.

**Comment by awaxa** [comment]
The GH Pages page represented most of the community contribution to this repo, I think.  It included more than just chatbot usage instructions, but also some general guidance about the channel.  I had been hoping to preserve the work of those users if it was possible.  I created this issue just to make sure it gets addressed at some point.

**Comment by awaxa** [comment]
Fingers crossed that 99f8f7278aad0be5e5e941fae29bdd2c18e7208c will be enough.

**Comment by liz-baker** [comment]
DERP, it was working fine. There's no `index.html` so it doesn't work for the root. Try this URL http://reddit-diabetes.github.io/diabot-plugins/irc.html

will use this ticket to rename irc.html to index.html, if that's OK with you guys

**Comment by awaxa** [comment]
![image](https://cloud.githubusercontent.com/assets/979580/10952025/7babb708-82f5-11e5-8680-5466d66b3274.png)

**Comment by awaxa** [comment]
:+1: for renaming to index.html

@TwelveBaud can you remember/think of any reason why we didn't do this years ago?

**Comment by liz-baker** [comment]
Maybe to keep it from being indexed? Since we're just using it for posterity I'm not terribly worried about it anyway.

**Comment by awaxa** [comment]
I guess the `reddit.html` link in the top nav bar was always broken?

**Comment by liz-baker** [comment]
Just looked through the history and didn't see that it ever existed. I might put together a similar page for lita-diabetes but I think that the r/diabetes wiki would probably be a better place to host a "how do chat" doc.

**Comment by TwelveBaud** [comment]
`index.html` and `reddit.html` were always TBD. I think we set this up before Reddit Wikis were generally available (I honestly have no idea) and we were reserving those pages for crash courses in diabetes and Redditing, with this page as a crash course in using diabot (and IRC in general). But only `irc.html` ever materialized, so it makes sense to be the new `index.html`.

**Comment by awaxa** [comment]
Thanks for the context, @TwelveBaud!
