### ISSUE TITLE
lastbg google chart api link

### ISSUE THREAD

**Issue by awaxa** [discord-diabetes/diabot-plugins#6]
[10:42:32] j^2: awaxa: project idea.  the `lastbg have it tie in with https://developers.google.com/chart/interactive/docs/examples so you can plot it out as a link :)

**Comment by jjasghar** [comment]
I figured it won't be too hard.  Maybe a simple convertion from the output to something like this: http://chart.apis.google.com/chart?chs=150x150&cht=qr&chl=Find%20me%20on%20irc.freenode.net/#reddit-diabetes&choe=UTF-8

**Comment by TwelveBaud** [comment]
http://imagecharteditor.appspot.com/

Some things to think about:
- Provide this automatically or require a certain parameter? (And alongside or in place of the standard list?)
- There's a ~375 character limit on IRC messages, and the default URL for the already simple Ponies v. Unicorns is ~200. Adding dates along the X axis adds even more pressure. URL shorteners? Use the [simple encoding format](https://developers.google.com/chart/image/docs/data_formats#simple)?
- Fixed Y axis or variable? If fixed, what methodology for using the mg/dL or mmol/L scale?
- This could be computationally complex. Data points for encoding (both Y and X), reasonable Y axis values, dates for the X axis, URL shortening if required...

**Comment by jjasghar** [comment]
- Provide this automatically or require a certain parameter? (And alongside or in place of the standard list?)
  - I see this as a option, maybe `lastbgchart` or something.  

Interesting.  I guess in my mind i was thinking of something simple with the `lastbg` that links to a shortened url that outputs whatever the `lastbg` is.

example: `[09:27] 200, [21:22] 226, [18:03] 156, [Sun 09:42] 118, [Sun 05:47] 43, [Sun 00:25] 89, [Sun 00:25] 341, [Sat 12:46] 85, [Sat 09:22] 99, and [Fri 23:45] 156`

It would ouput 2 for today, 4 for sun, 2 for sat, and one for friday.  

y axis being the bloodsugar, and x axis being time, days/hour on whatever the case maybe.

**Comment by TwelveBaud** [comment]
http://chart.apis.google.com/chart?chxl=0:|2-May|3-May|4-May&chxp=0,0.4,42,83.6&chxr=1,43,341&chxt=x,y&chs=640x400&cht=lxy&chco=000000&chd=s:9wtkgaaOKA,glXPAJ9JMX&chdlp=b&chls=2&chma=5,5,5,25 (191 chars)

http://bit.ly/LrSEwd (20 chars)

... I guess that could work.
